site_name: SLISE
site_url: https://edahelsinki.github.io/pyslise
repo_url: https://github.com/edahelsinki/pyslise
edit_uri: ""

theme:
  name: material
  icon:
    logo: material/book-open
  favicon: pyslise_icon.webp
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

nav:
  - Home: "index.md"
  - Documentation:
      - slise: docs/slise.md
      - slise.slise: docs/slise.slise.md
      - slise.data: docs/slise.data.md
      - slise.initialisation: docs/slise.initialisation.md
      - slise.optimisation: docs/slise.optimisation.md
      - slise.plot: docs/slise.plot.md
      - slise.utils: docs/slise.utils.md
  - Links:
      - GitHub: https://github.com/edahelsinki/pyslise
      - PyPI: https://pypi.org/project/slise/
      - Original conference paper: https://rdcu.be/bVbda
      - Robust regression paper: https://rdcu.be/cFRHD
      - Local Explantions paper: https://doi.org/10.3389/fcomp.2023.1143904
      - Examples: https://github.com/edahelsinki/pyslise/tree/master/examples

plugins:
  # - offline
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_root_heading: True
  - include-markdown
